### PR TITLE
Add `NodeInjectionService` (#153, solution 2)

### LINKED ISSUE #153: Discussion: Future of command contexts and making contextual information more verbose
Myself personally, and I'd assume some others have stumbled upon the issue of not being able to detremine what really happened upon   command execution. 

@Nihlus pointed out three distinct solutions that all have various pros in cons and regards to how to solve this issue.

### Solution 1: Expanding `ICommandContext`

This one is a simple change, and would add an `IChildNode` or the likes to the pre-existing `ICommandContext` and it's derivitives.

This would more than likely be an `Optional<T>` property, seeing as contexts (namely `InteractionContext`) have had their usage scope expanded to more than just traditional commands (re: Interactivity)

### Solution 2: Node injection service

This change is also relatively simple, and piggybacks off a similar system that's currently in use by the command responders.

A new service would be added, by the names of `NodeInjectionService` or the likes. It will posses the current command node being invoked, much like `ContextInjectionService`.

## Solution 3: Reworking context architecture

This solution is largest of the three, and involves reworking how contexts are handled and constructed. 

Concrete types would posess a node property only if applicable, being omitted from the others.

`ICommandContext` would be minimally affected by this, as new base classes would be rewritten to derive it, especially in the case of interactions, where an `IInteractionContext` class would be spawned, and `InteractionContext` and `InteractionCommandContext` would derive from the former.

### PR DESCRIPTION
**Pull request by VelvetThePanda**
This PR implements support for solution 2 mentioned in #153.

I've yet to add tests (should be fairly simple). Solution 1 *may* have been easier considering interactivity being rewritten to piggyback off of Remora.Commands, but I already had the code written, and hadn't pushed. 

If solution one is preferred, 90% of the code can be reused so feel free to poke about that. cc @Nihlus

( Fixes #153 )

### CODE REVIEW

**Comment by VelvetThePanda** [comment]
Fixes #153

**Comment by Nihlus** [comment]
I'm kind of still in the solution 3 camp, myself. That said, this is not orthogonal to that and could be merged as a stopgap measure.

**Comment by VelvetThePanda** [comment]
The third option is probably the best? Certainly a fair bit more work to implement, so I second this being a stopgap.

**Comment by Nihlus** [comment]
You've got some xUnit warnings to take care of.

**Comment by Nihlus** [comment]
Closing as moot.

**Pull request closed without merging**
