### PR TITLE
Improve memory pressure in ImagePacker by not allocating extra byte[] buffers if they can be retrieved from the Stream directly

### PR DESCRIPTION
**Pull request by uwx**
ImagePacker.PackImageAsync creates a new `byte[]` out of the Stream even if a MemoryStream is passed; if the input stream is not a MemoryStream, it allocates *two* byte arrays with the size of the image being uploaded.

This PR fixes this by using TryGetBuffer if the underlying Stream is a MemoryBuffer and allows it, falling back to ToArray otherwise. When the Stream has to be copied to a buffer, we also retrieve the MemoryStream's underlying buffer instead of allocating a new one.

### CODE REVIEW

**Comment by uwx** [comment]
Depends on https://github.com/Remora/Remora.Rest/pull/15

**Comment by uwx** [comment]
Will undraft this PR when I test it.

**Comment by uwx** [comment]
Tested by uploading a bunch of custom emoji and it's working fine.

**Comment by Nihlus** [comment]
You've got some build errors you need to take care of.

**Comment by uwx** [comment]
Build error is due to the dependency on https://github.com/Remora/Remora.Rest/pull/15, which is not yet on NuGet, so there's not much I can do there.

**Comment by Nihlus** [comment]
Remora.Rest has now been updated. Could you rebase this PR onto the latest main branch?

**Comment by uwx** [comment]
Did that

**Pull request merged**
